# Generated by Django 2.2.7 on 2019-11-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('A', 'ACTION'), ('C', 'CONCEPT'), ('O', 'OBJECT')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acocatalog.CoreTerm')),
            ],
        ),
    ]
